# 
# Synthesis run script generated by Vivado
# 

set_param general.maxBackupLogs 0
set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-3
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.cache/wt [current_project]
set_property parent.project_path C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/coes/score.coe
add_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/coes/MemTextures.coe
add_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/coes/winner.coe
add_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/coes/grid.coe
add_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/coes/About.coe
add_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/coes/Instructions.coe
add_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/coes/PSelect.coe
add_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/coes/Initial.coe
add_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/coes/Pointer.coe
add_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/coes/all.coe
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/MemScore_synth_1/MemScore.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/MemScore_synth_1/MemScore.dcp]
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/MemTextures_synth_1/MemTextures.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/MemTextures_synth_1/MemTextures.dcp]
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/MemWinner_synth_1/MemWinner.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/MemWinner_synth_1/MemWinner.dcp]
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/MemFaces_synth_1/MemFaces.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/MemFaces_synth_1/MemFaces.dcp]
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/Clock8346_synth_1/Clock8346.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/Clock8346_synth_1/Clock8346.dcp]
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/Mem_synth_1/Mem.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/Mem_synth_1/Mem.dcp]
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/About_synth_1/About.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/About_synth_1/About.dcp]
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/Instructions_synth_1/Instructions.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/Instructions_synth_1/Instructions.dcp]
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/PSelect_synth_1/PSelect.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/PSelect_synth_1/PSelect.dcp]
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/Initial_synth_1/Initial.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/Initial_synth_1/Initial.dcp]
add_files -quiet C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/Pointer_synth_1/Pointer.dcp
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.runs/Pointer_synth_1/Pointer.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/lfsr_random.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/ToPixelWinner.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/ToPixelScore.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/ToPixelFaces.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/ToPixel.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/TextAndRowToAddr.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/ScoreAndRowToAddr.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/RowToAddr.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Reg7.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Reg10.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Reg.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/FaceAndRowToAddr.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Stack.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Register7.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Register5.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/random.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/new/PSelectControl.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/new/PointerControl.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/new/InstructionsControl.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/new/InitialControl.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/BlockRamWinner.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/BlockRamTextures.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/BlockRamScore.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/BlockRamFaces.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/new/AboutControl.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/test_button.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/new/SelectFSM.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Reset_Mode.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Randomize.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Play_mode.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/OpenRest_module.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Initialize.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/new/DigitFSM.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/debounce.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/CoordToAddr.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/new/BCD2SSD.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/new/Menu_Control.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Imgur.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/new/SevSeg_top.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Normalizer.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/DigitsForScore.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Cursor.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/Control.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/BlockRamGrid.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/top_level.vhd
  C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/sources_1/imports/VHDL/BlockRamIniScreen.vhd
}
read_xdc C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/constrs_1/imports/Constraints/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Vfor/Documents/GitHub/Minesweeper_Vivado/Minesweeper_Vivado.srcs/constrs_1/imports/Constraints/Nexys4DDR_Master.xdc]

catch { write_hwdef -file Top_Level.hwdef }
synth_design -top Top_Level -part xc7a100tcsg324-3
write_checkpoint -noxdef Top_Level.dcp
catch { report_utilization -file Top_Level_utilization_synth.rpt -pb Top_Level_utilization_synth.pb }
